baseurl: https://icyleaf.com/
title: icyleaf
theme: nicesima
languageCode: zh
defaultContentLanguage: zh
disableHugoGeneratorInject: true
hasCJKLanguage: true
enableEmoji: true
enableRobotsTXT: true
paginate: 20
disqusShortname: icyleaf
canonifyURLs: true

params:
  # global settings
  homepage:
    showProfile: true
    showPosts: true
  homeMode: posts
  author: icyleaf
  avatar: images/icyleaf-icon.png
  description: 日常写代码热爱户外的梦想家
  subtitle: 你好，我是 icyleaf
  since: 2005
  mark: 🍺
  enableComment: disqus
  hideHUGOSupport: true
  hidePermalink: true
  hideSeries: false
  showFullTextinRSS: true
  googleAnalyticsUserID: G-TKQBZ7R259

  # utteranc:
  #   repo: "icyleaf/icyleaf.com" # The repo to store comments
  #   issueTerm: "pathname"
  #   label: "✨💬✨"
  #   theme: "github-light"
  #   CrossOrigin: "anonymous"
  #   async: true

  # giscus:
  #   repo: icyleaf/icyleaf.com
  #   repoId: MDEwOlJlcG9zaXRvcnk1NDg4MDA5Mg==
  #   categoryId: DIC_kwDOA0VnXM4CQ0mG
  #   # theme: /css/themes/giscus.css
  #   localPreview: true

  socials:
    - name: github
      link: https://github.com/icyleaf
    - name: twitter
      link: https://twitter.com/icyleaf
    - name: facebook
      link: https://www.facebook.com/icyleaf
    - name: linkedin
      link: https://www.linkedin.com/in/icyleaf
    - name: instagram
      link: https://www.instagram.com/icyleaf/
    - name: douban
      link: https://www.douban.com/people/icyleaf

  # posts settings
  toc: true # 是否开启目录

permalinks:
  posts: /:year/:month/:slug
  page: /:filename

menu:
  main:
    - name: Posts
      weight: 10
      identifier: posts
      url: /posts
    - name: Tags
      weight: 20
      identifier: tags
      url: /tags
    - name: Categories
      weight: 20
      identifier: categories
      url: /categories
    - name: About
      weight: 100
      identifier: about
      url: /about

pygmentsUseClasses: true # 使用自定义的代码高亮样式
markup:
  highlight:
    codeFences: true
    anchorLineNos: false
    guessSyntax: false
    hl_Lines:
    lineAnchors:
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    style: tomorrow-night
    tabWidth: 4
